src/datum.h, src/hdf5_back.cc, src/hdf5_back.h, src/query_backend.h, src/recorder.cc, src/recorder.h, src/sqlite_back.cc, src/sqlite_back.h, tests/hdf5_back_tests.cc, tests/recorder_tests.cc, tests/sim_init_tests.cc, tests/sqlite_back_tests.cc
This adds a subclass of recorder that does not inject the SimId and gives you raw table writing. This is needed for the more general case of writing to the database, and in particular for cymetric or any other analysis tool. In such situations SimIds are not necessarily semantically meaningful. For example, aggregation over many simulations will make any SimId field meaningless. Since folks may want to store any kind of data a raw recorder is needed. A subclass API turned out to be cleaner than adding new member functions.
This is dependent on #1061, which should be merged in first.
=> Raw Recorder

cli/cycpp.py, src/toolkit/res_buf.h, src/toolkit/res_manip.cc, src/toolkit/res_manip.h, tests/toolkit/res_manip_tests.cc
ResBuf prior to this commit was broken.  It tried to use the an overload
of the ResCast function in resource.h that didn't exist.  Since the ResCast
overload needed isn't terribly likely to be needed outside of resource
buffer(s), I decided it fit well in the toolkit.
Previously, the code generated by cycpp for setting resource buffer capacities
in InitFrom (db) assumed that the 'capacity' key for the buffer member
dictionary was a literal value stored in the database explicitly.  This
relaxes that assumption and instead assumes the 'capacity' key is literal code
that should be pasted in.  Now arbitrary expressions, etc. can be used to
compute capacities based on other member variables.  The tradeoff is that all
referenced member variables in these expressions must be defined/pragma'd …
=> modify resbuf code generation. Add missing ResCast funcs.

src/bid_portfolio.h, tests/bid_portfolio_tests.cc
For @mbmcgarry, this removes commodity checking in bid portfolios. This is a check that used to necessary, bid portfolios used to require a single commodity, but that has been relaxed, and this was missed on that update. This PR preserves ABI stability, noting what is deprecated.
=> deprecates commodity checking and related API in bid portfolios

src/composition.cc, src/material.cc, src/material.h, tests/material_tests.cc, tests/sim_init_tests.cc
* lazy decay option decays materials every time the Material::comp function is
called.
* Added ability to call Material::Decay with a negative time argument that
causes the decay operation to run with the material's context's current
time.  Throws if the material has a NULL context.
* fixed sim_init tests - they previously counted on optional normalization for
material compositions that has now changed.  Note that API is identical -
the doc comments for the relevant functions explicitly states that returned
composition are not normalized.
=> lazy decay option and misc cleanups and tweaks

src/material.cc, tests/material_tests.cc
Previously, Transmute left prev_decay_time alone resulting in strange/wrong
results if, for example, a material had accumulated several time steps of
delta t since last decay - and then was transmuted - say burned as reactor
fuel.  The resulting material would have still remembered its previous decay
delta t.  Causing bad physics.
This fix changes the behavior to assume that the Transmute caller has
calculated the new target composition to be accurate for the current
simulation time - i.e. no accumulated decay delta t.
=> Transmute resets prev_decay_time now

agents/sink.cc, agents/sink.h, agents/source.cc, agents/source.h, src/cyclus.h, src/mock_sim.cc, src/mock_sim.h, src/sqlite_back.cc, src/sqlite_back.h, tests/mock_sim_tests.cc
This isn't done yet - it still needs api docs and dev guide docs.  But I wanted to hear thoughts/suggestions before I start polishing it up.  It allows someone to write code like this:
```c++
cyclus::CompMap m;
m[id("U238")] = 1.0;
Composition::Ptr depleted = Composition::CreateFromMass(m);
std::string config =
"<commod>enriched_u</commod>"
"<recipe_name>depleted</recipe_name>"
"<capacity>10</capacity>";
int dur = 10;
cyclus::MockSim sim(cyclus::AgentSpec(":agents:Source"), config, dur);
sim.AddSink("enriched_u").Finalize();
sim.AddRecipe("depleted", depleted);
sim.Run();
```
And then you can write gtest tests like this:
```c++
QueryResult qr = sim.db().Query("Transactions", NULL);
EXPECT_EQ(10, qr.rows.size()) << "expected 10 transactions, got " << qr.rows.size();
```
You can add as many …
=> adds helpers for running mock simulations to test archetypes.

src/material.cc, src/material.h
=> add back old Material::comp() const for abi stability. It throws.

src/material.cc, src/mock_sim.cc, tests/material_tests.cc
This cherry-picks the yosemite fixes needed for running cyclus (and cymetric) on mac. Perhaps @mbmcgarry or @deniadjokic could reveiw and merge, since they were experiancing these issues.  This closes #1088 and #1089.
=> Yosemite fixes

cli/cycpp.py, src/toolkit/enrichment.cc, src/toolkit/enrichment.h, tests/toolkit/enrichment_tests.cc
Added a toolkit function NonFissileMultiplier that is the ratio of total fuel over fissile material.  This is used when calculating necessary feed quantities for input materials into the enrichment facility that include components beyond U-235 and U-238.  Needed for the new cycamore EnrichmentFacility.
Also updated documentation for UraniumAssay and FeedQty to clarify that they assume the material is entirely comprised of fissile isotopes of uranium.
=> Fix feed qty

release/abi_whitelist.py, release/smbchk.py
This adds a minimal whitelist to allow #1084 to pass. Note that smbchk.py still can't be found by our CI. But this should allow us to minimally move forward...
=> a bandaid to address issues in #1084

src/agent.cc, src/agent.h, tests/agent_class_tests.cc
to enable other agents to manually specify lifetimes.
=> protected access is not enough - need a setter for Agent::lifetime

agents/sink.h, cli/cycpp.py, tests/cycpp_tests.py
Also cleaned up xml schema generation.  Now it uses xml.dom.minidom to prettify and auto-escapes quotes and backslashes (e.g. for newlines).  This results in custom-schema snippets being much easier for archetype devs to write (and also makes the cyclus.github.com docs about them un-incorrect).
Full disclosure - there are some lines much longer than 80 chars - most/all of these are in the tests and are long because they are 'generated' snippets from the filters used as hybrid regression/unit tests (the unit test factor comes from the fact that I carefully verified the generated snippets to be correct).  In case we ever tweak the filters in the future, we can easily regenerate the changed "regression" snippets and verify correctness.  This is why I don't think it prudent to make them …
=> recursive container support for cycpp

cli/cycpp.py
This is needed for the separations facility - so quicker review is better.
Previously template parsing assumed that all commas were at the current nesting level for
template args.  This is not true when templates become nested like this:
```c++
std::map<std::string, std::pair<int, double> >
```
Previously the parse would splitting on the comma inside the pair template
brackets as a part of the outer map's template args.  This is now fixed.
The new recursive support for templated types enabled recursive specification
of alias's.  There were a few spots in the code that weren't correctly updated
to deal with this.  Those are also addressed here.
=> fix handling of nested template parsing. fixed alias handling.

src/toolkit/res_buf.h
This makes recipe based FCO sims go from ~15 min to ~2 min.  Also I threw in a one line fix for sim_init where prototypes added post simulation init weren't snapshotted properly (the new deployinst utilizes does this and won't work correctly without this fix).
=> faster resbuf

src/toolkit/matl_buy_policy.cc, src/toolkit/matl_buy_policy.h, tests/toolkit/matl_buy_policy_tests.cc
This adds a throughput member to buy policies and matches its Init method signature with the sell policy. This replaces #1135 and should be in 1.3 because of its use for the developer tutorial.
=> buy policy throughput

release/smbchk.py, src/exchange_manager.h, src/trade_executor.h
Previously, if a facility modified a received resource in its Accept[Matl/Prod]Trades function, DRE wouldn't record the traded resource until after AcceptTrades returned - resulting in the incorrect resource id and state being recorded as what was transacted.  This tweaks DRE to record the trades and resource info after trades are completely resolved but before the materials are sent to the requesters.  Very tricky bug to find!
=> Fix trade record

README.rst
The previous instructions were dangerous for macs. Mixing homebrew and macports is risky. People who use homebrew should stick to homebrew. The new instructions suggest the right thing - people using homebrew should replace port commands with brew commands.
I know you're trying to get a release out, so take or leave this. I'm just going over the docs and whatnot to try to be helpful with fresher eyes.
=> minor change to readme, for MacOSX safety. 

src/mock_sim.cc, src/mock_sim.h, tests/mock_sim_tests.cc
allows testing of end-of-life behavior of agents.
=> mocksim can now take custom lifetimes for tested agents.

circle.yml, docker/README.md, docker/cyclus-deps/Dockerfile, docker/dockerbuild.sh, docker/dockercyclus.sh
Built on #1201 - fixes a few other changes required for python3 stuff to work.
=> Python 3 in cyclus-deps instead of python 2

cli/cycpp.py, tests/cycpp_tests.h, tests/cycpp_tests.py
'internal' tag now makes state variables invisible in the xml schema, but
still persisted/loaded normally.  'internal' vars can have default values.
'derived_init' vars now show up in the xml schema as optional and the
derived_init value is overridden if a user specifies the value in the schema.
If a var is both internal and derived_init, then it is not in the schema but
can still have a default value specified.
=> Add internal tag to cycpp. Modify derived_init tag behavior:

src/resource_exchange.h
This eliminates one of the most significant sources of non-determinism remaining.  In simulations I've run, this is enough to get ~exact reproducability.  There are other things like modifying the ``Arc::operator<`` function that could also increase determinism, and also using the ordered traders set for calling accept/get matl trades functions, but lets only do that as needed as it has a tendency to reduce performance, etc.
=> call agents' get[matl/prod][requests/bids] in deterministic order

share/CMakeLists.txt, share/cyclus-flat.rng.in, share/cyclus.rng.in, src/composition.cc, src/composition.h, src/context.cc, src/context.h, src/material.cc, src/sim_init.cc, src/xml_file_loader.cc, tests/CMakeLists.txt, tests/composition_tests.cc, tests/input/CMakeLists.txt, tests/input/custom_dt.xml, tests/input/custom_dt_flat.xml, tests/integ_tests.cc, tests/material_tests.cc
Note that there are a couple of TODOs I added to the code to help remind us to update/remove the int casting when backends get uint64_t support.
=> Implement CEP23 - custom time step duration

src/infile_tree.cc, src/infile_tree.h, src/prog_translator.h, src/relax_ng_validator.cc, src/relax_ng_validator.h, src/sqlite_db.cc, src/sqlite_db.h, src/toolkit/building_manager.cc, src/toolkit/building_manager.h, src/toolkit/infile_converters.cc, src/xml_parser.cc, src/xml_parser.h, stubs/CMakeLists.txt, tests/xml_parser_tests.cc
This buys us some time to decide how we want to deal with c++11 support for stubs, cycamore, etc. by not leaking the c++11 requiring headers (libxml++). And it makes compiling archetypes simpler anyway. Addresses a good chunk of #1199.
=> fix 3rd party dependency header leakage

src/hdf5_back.cc, src/hdf5_back.h, src/query_backend.h
This adds a Close() method to FullBackend to allow it to behave more like a true file object when used from libcyclus.  This was implemented because HDF5 keeps an internal cache of datasets, datatypes, and so on that is not cleared until the HDF5 object is itself closed.  Not clearing this cache was causing problems if you had:
1. run a simulation
2. opened a file with cymetric
3. left the interpreter open (via IPython, xonsh, etc)
4. run a new simulation in another process that used the same database
5. querying the new simulation data via cymetric would have partial, malformed data at best.
This PR allows cymetric to fully close the backend and the open an new handle if needed.
@hodger, can you please review.
=> added Close() to FullBackend

share/dbtypes.json
All of these are maps containing a pair. They appear in hdf5_back.cc but did not previously exist at all in dbtypes.json. 
@scopatz could you please review?
=> Added 4 supported HDF5 types to dbtypes.json 

tests/GoogleTest/gtest/gtest-all.cc, tests/GoogleTest/gtest/gtest.h
This fixes this error:
```
cyclus_unit_tests: symbol lookup error: cyclus_unit_tests: undefined symbol: _ZNK7testing7Message9GetStringB5cxx11Ev
```
that I have been getting just recently when I try to run the unit tests after a successful compile.  Strange.  I've looked at the so's with nm and have also confirmed proper linking with ldd.  It must be some strange incompatibility with the c++ tricks gtest was doing with new c11 compiler details.  In any case, the new gtest amalg does not exhibit the problem.
=> update gtest amalgamation

tests/agent_tests/agent_tests.cc, tests/agent_tests/agent_tests.h, tests/agent_tests/facility_tests.cc, tests/agent_tests/facility_tests.h
The FacilityTests initialization does not honor the normal initialization
guarantees for archetypes.  And so any type of remotely sophisticated
configuration validation of archetypes will be triggered to fail if we try to
call methods like e.g. Tick, Tock, Build, etc.  Remove these calls.  We
already know the agents satisfy the Agent class interface implicitly by being
able to load them and cast/assign them to Agent*/Facility*/etc.  From now on,
only call state-reporting functions with no side-effects in these tests.
=> Fix parametrized FacilityTests

src/bid_portfolio.cc, src/bid_portfolio.h
Cyclus uses to crash when a bid with a quantity = 0 is offered (creating a *nan* in **exchange_translator.h:** ***void TranslateCapacities( ... )*** method )
Now it trows an error.
=> Trow error when a bid with quantity <=0 is offered

release/smbchk.py
I had a test failure on a fresh Ubuntu install from source complaining about the ABI test.
=> adds a private new decay function to composition

share/cyclus-flat.rng.in, share/cyclus.rng.in, src/context.cc, src/context.h, src/infile_tree.h, src/sim_init.cc, src/timer.cc, src/timer.h, src/xml_file_loader.cc, tests/input/inventory.xml, tests/input/inventory_compact.xml, tests/input/inventory_compact_false.xml, tests/input/inventory_false.xml, tests/integ_tests.cc, tests/test_inventories.py
Built on #1227 - so this will need a rebase after that goes in.  This is still a work in progress and needs tests.  Closes #1223.
Input file now has two new optional config params in control section:
```xml
<explicit_inventory>[bool]</explicit_inventory>
<explicit_inventory_compact>[bool]</explicit_inventory_compact>
```
which each generate new correspondingly named tables in the database.  There is one main design decision we still need to make:
* We have the ability to record inventories separately by buffer name - i.e. facilities with multiple buffers can have their different buffer inventories recorded separately (e.g. fresh_fuel, in_core, spent_fuel).  This is how I've implemented it here.  The alternative is to just squash all different buffers' materials together and record a …
=> Add optional explicit agent inventory tables

src/cyc_limits.h, src/exchange_graph.cc, src/greedy_solver.cc
Previously, some exclusivity arcs were being terminated (set to zero) because
floating point comparisons failed that should have succeeded such as:
29565 <= 29564.999999999994
This uses ULP comparisons to determine closeness of floats more robustly
handling cases of numbers that should be treated as ~identical.
This resolves some issues Baptiste has been having in his FCO work.
=> be careful with exclusivity float comparisons in DRE

src/hdf5_back_gen.py
This is in reference to #1236.
On my clean install of 14.04, this fix allows to cyclus to install successfully with no hdf5_back recursion errors. I sorted out unicode characters at the point when we pull in data from dbtypes.json. 
Additionally, this allows almost all unit tests to pass, except the following 3: 
```[----------] Global test environment tear-down
[==========] 553 tests from 109 test cases ran. (30570 ms total)
[  PASSED  ] 550 tests.```
```[  FAILED  ] 3 tests, listed below:```
```[  FAILED  ] ProgTranslatorTests.translation```
```[  FAILED  ] Hdf5BackTests.ReadWriteDouble```
```[  FAILED  ] Hdf5BackTest.ReadWriteAll```
In terms of the ReadWriteDouble, the generated double code looks to be correct.
```
case DOUBLE: {
double x = *reinterpret_cast<double*>(buf + offset); …
```
=> Fix for hdf5_back_gen.py compatibility issues.

cli/cyclus.cc
As @rwcarlsen asked, with this modification, one can now remove the catch of exception  by setting CYCLUS_NO_EXCEPTION environment variable to anything but 0.
Not sure the choose of the variable name is the best... I let you guys suggest something better
=> read CYCLUS_NO_EXCEPTION env variable to know if catching exception is require

cli/cycpp.py, cmake/UseCyclus.cmake, tests/cycpp_tests.py
On boost v1.60.0, there are some terrible anonymous namespaces that are hidden by a macro call stack. In particular in `boost/type_traits/detail/has_postfix_operator.hpp`, we have effectively, 
```C++
namespace boost {
namespace detail {
// This namespace ensures that argument-dependent name lookup does not mess things up.
namespace BOOST_JOIN(BOOST_TT_TRAIT_NAME,_impl) {
struct no_operator { };
}
}
}
```
Where the `BOOST_JOIN()` macro is defined as, 
```C++
#define BOOST_JOIN( X, Y ) BOOST_DO_JOIN( X, Y )
#define BOOST_DO_JOIN( X, Y ) BOOST_DO_JOIN2(X,Y)
#define BOOST_DO_JOIN2( X, Y ) X##Y
```
This was causing cycpp to fail with the following error:
```console
Traceback (most recent call last):
File "/home/scopatz/miniconda3/conda-bld/work/cyclus-cd572972b3dbf4b6d24a8e500ff270a42e8b2c7d/c …
```
=> Fix for anonymous namespaces, triggered by boost

.gitignore, CMakeLists.txt, install.py
These are in support of building on a conda-forge based environment. Using `./install.py --hdf5_root=/path/to/conda` will build on this branch. Note that there are some coin-based segfaults in testing I am seeing locally, but I don't think that this is the fault of these changes.
=> Installation Improvements

src/toolkit/matl_sell_policy.cc
Before SMP was Poping mat from ResBuf using Pop(qty,eps) but using a relative eps of 1e-12.
As [discussed](https://groups.google.com/forum/#!topic/cyclus-dev/d25nGI9dYH0), I change it to absolute value for eps: `cyclus:eps_rsrc()`
=> Correct the way sell_mat_policy (SMP) was handling the Pop() on ResBuf

.clang-format
Offering a clang-format file that has a couple of tweaks on topics that are considered optional in GSG.
Still no remedy to avoid reformatting std::operator<< calls.
=> clang-format config file: Small tweaks from Google Style Guide in mostly optional parts.

cmake/UseCyclus.cmake, stubs/src/CMakeLists.txt
This is an alternative solution to cycamore issue [#419](https://github.com/cyclus/cycamore/issues/419#issuecomment-239237669) from #1268 and #1269.
This solution is simply a suppression of the HEADER installation instruction from the UseCyclus.cmake file, as well as the src/CMakefile.txt of the cystub....
Please see for the PR #1268 and #1269 for the other fixing proposition
=> Fix header install path: addressing cycamore issue #419

src/error.h, src/prog_translator.cc, src/prog_translator.h, src/toolkit/building_manager.cc, src/toolkit/building_manager.h, tests/prog_translator_tests.cc
This addresses #1279 by returning to the situation where there is no leakage of COIN headers and thus no need for any archetypes that use the `building_manager` to know about COIN headers.
The previous version of this caused an API/ABI change that, although unlikely to be a problem for anyone, is contrary to our stability philosophy.  This version maintains the API/ABI stability by
* changing all references (2 in `prog_translator.h` & 3 in `building_manager.cc`) of `ProgTranslator::Context` to refer to `ProgTranslatorContext`
* reintroducing the `ProgTranslator::Context` class
* explicitly defining its constructor and destructor
* implementing said con/destructors to throw a DepricatedApiError
* adding the DepricatedApiError
* adding a test to demonstrate that this error is thrown
=> Deprecate `ProgTranslator::Context` without changing API/ABI.

src/hdf5_back_gen.py
I encountered errors with incorrect syntax for python2 here.
```
Traceback (most recent call last):
File "/home/wilsonp/UW/research/software/cyclus/cyclus/src/hdf5_back_gen.py", line 1093, in <module>
main()
File "/home/wilsonp/UW/research/software/cyclus/cyclus/src/hdf5_back_gen.py", line 1082, in main
CPPGEN = CppGen()
File "/home/wilsonp/UW/research/software/cyclus/cyclus/src/hdf5_back_gen.py", line 146, in __init__
super().__init__(tree=tree)
TypeError: super() takes at least 1 argument (0 given)
```
I'm not sure why we haven't noticed before, but it scrolls past quickly and doesn't cause failure.  Perhaps our build process should fail when this step fails - I think errors at this step has been an issue before.
I need someone else to test on Python3 ( @hodger , @scopatz )
=> Fix for python2

CMakeLists.txt, install.py
This extends the CMake version handling to extend beyond the case where the full git repo and git binary are available, such as in certain conda recipes or when building directly from a tarball.  This adds the `CORE_VERSION` variable to the build system and allows it to be set via `install.py --core-version=X.X.X`
Proof that this works is available in https://github.com/conda-forge/cyclus-feedstock/pull/3, which was failing on the 1.4.0-rc3 tag but works with my branch.
=> more robust core version handling

DEPENDENCIES.rst, INSTALL.rst
Add include flag in `INSTALL.rst` and `DEPENDENCY.rst` to allow automatic hook in some page of the fuel cycle.org website.
@gonuke @mbmcgarry: could you review that quickly so I can try if everything is working as expected (already a part of it, just want to be sure it is fully working -- from the wget to the inclusion...)
thx
=> Add include flag

src/bid.h, src/bid_portfolio.h, src/request.h, src/request_portfolio.h
This supposedly fix the following ABI change:
> -cyclus::Bid<cyclus::Material>::Bid(cyclus::Request<cyclus::Material>*, boost::shared_ptr<cyclus::Material>, cyclus::Trader*, boost::shared_ptr<cyclus::              BidPortfolio<cyclus::Material> >, bool) +cyclus::Bid<cyclus::Material>::Bid(cyclus::Request<cyclus::Material>*, boost::shared_ptr<cyclus::Material>, cyclus::Trader*, boost::shared_ptr<cyclus::              BidPortfolio<cyclus::Material> >, bool, double)
> 
> -cyclus::Bid<cyclus::Material>::Bid(cyclus::Request<cyclus::Material>*, boost::shared_ptr<cyclus::Material>, cyclus::Trader*, boost::shared_ptr<cyclus::BidPortfolio<cyclus::Material> >, bool)
> +cyclus::Bid<cyclus::Material>::Bid(cyclus::Request<cyclus::Material>*, boost::shared_ptr<cyclus::Material>, cyclus::Trader*, …
=> I don't understand why... Abi fix

src/mock_sim.cc, src/pyhooks.cc, src/pyhooks.h
This fixes the segfault that is in the test suite that was caused by numpy. It also cleans up the pyhooks header so downstream packages don't have to have the same compile-time value of `CYCLUS_WITH_PYTHON` that cyclus had.
=> Fixed numpy segfault

.gitignore, cli/cyclus.cc, cyclus/cpp_cyclus.pxd, cyclus/lib.pyx, cyclus/main.py, src/cyclus.h, src/pyhooks.cc, src/pyhooks.h, src/pyinfile.pxd, src/pyinfile.pyx, src/toolkit/infile_converters.cc, src/toolkit/infile_converters.h, src/xml_file_loader.cc, tests/toolkit/infile_converters_tests.cc
This adds the ability to use Python files as input files to Cyclus.  This PR builds off of the server PR and is probably long overdue.
=> Python Simulation Input Files

src/hdf5_back_gen.py
This should take care of #1354.
Forgot that using * syntax to unpack a list was introduced in Python 3.
@scopatz @bam241
=> Python 2.7 compatibility fix for hdf5_back_gen.py

cli/cycpp.py, cyclus/gentypesystem.py
This fix ensures that Python 2.7's `unicode` type is treated the same as `str` while generating the typesystem. Previously, `unicode` was not handled, causing list comprehensions to produce empty lists, resulting in incorrect code generation.
@bam241 Please let me know if this solves #1356
=> python2.7 fix

cyclus/gentypesystem.py, src/hdf5_back_gen.py, src/query_backend.h, tests/hdf5_back_gen_tests.py
Added all variants of `MAP_STRING_MAP_INT_DOUBLE`, and fixed a couple `gentypesystem.py` bugs. Plus a few PEP8 changes to `hdf5_back_gen.py`
@scopatz
=> Hdf5 support for map_string_map_int_double type variations

src/hdf5_back_gen.py, src/query_backend.h
With the addition of these types: 
- LIST_PAIR_INT_INT
- MAP_STRING_PAIR_STRING_VECTOR_DOUBLE
- MAP_STRING_MAP_STRING_INT
- VECTOR_PAIR_PAIR_DOUBLE_DOUBLE_MAP_STRING_DOUBLE
(and their variations), the Hdf5 backend now supports all SQLite-supported datatypes.
Types in `query_backend.h` that are not supported yet:
- Cyclus resource types 
- (VL_)VECTOR_BOOL (requires specialization, in progress)
- (VL_)SET_BOOL (requires some restraints I haven't yet implemented)
@scopatz
=> Hdf5 backend support for all current SQLite types

src/hdf5_back.cc.in, src/sqlite_back.cc, tests/test_cycluslib.py
This PR fixes a few Hdf5-related bugs that allow Schema to function properly. The main problem was reading and writing the shape attribute- this now works. 
@scopatz
=> Fix for Hdf5Back::Schema

src/hdf5_back.cc.in, src/hdf5_back.h.in
LoadTableTypes now calls CreateTable when an unrecognized table is being added. This is required for merging two Hdf5 output files together if the same tables are not present in both.
=> changes for hdf5 table merging

src/hdf5_back.cc.in
This fixes the `Schema` bug which was throwing a malloc error when trying to merge two HDF5 databases which use the Separations archetype. 
We were allocating the wrong number of elements in the `shape` vector in `Hdf5Back::Schema`. Instead of allocating for the number of elements, we were only doing the number of dimensions (which was always 1).
=> Fix to Schema for rickshaw database merge

src/CMakeLists.txt
This adds some compile flags for transmutagen. Closes #1389.  @FlanFlanagan @bam241
=> clang transmutagen flags

Dockerfile, README.rst, circle.yml, tests/helper.py
this aims to:
- switch from Circle 1.0 API to Circle 2.0
- trigger `Cycamore`/`Cymetric` develop CI build when PR on develop (with integration of the results)
- add all previous feature of the circle.yml as separated item.
there is the possibility in GitHub to integrate the different tests in the PR checking, and have some of them not required for the merge (as the `Cycamore`/`Cymetric` run)
you can see [here](https://circleci.com/gh/cyclus/workflows) the results of the change in the Cyclus CircleCI workflow
Note: I still did not add the trigger of `Cycamore/master` and `Cymetric/master` against `Cyclus/develop`, this will also need some change on Cycamore/Cymetric (the way I picture it...)
PS: some DockerFile can now be removed and/or modified..
=> Triggering Cycamore/Cymetric -- switching to CircleCI 2.0

CMakeLists.txt, cyclus/CMakeLists.txt
This fixes an issue where Python extension modules were not actually getting the `CMAKE_INSTALL_RPATH` set.  With this, building off of conda locally never requires you to set the `LD_LIBRARY_PATH`
=> Python Extension Module RPATH

src/cyclus.h
This adds position header file into cyclus.h that has been missing this whole time.
=> Added position toolkit inclusion statement

tests/agent_tests/agent_tests.cc
A segfault was discovered in ShortTermStorage that was being caused by the simulation information not being set up properly.
=> Fix for downstream segfaults in Unit tests

src/material.cc
Also, fixes 4-space indents to 2-space. CC @FlanFlanagan
=> Filter out NaNs from decay heat calculation

src/cyclus.h
This PR adds the missing toolkit/position.h file from Cyclus.
This fixes https://github.com/cyclus/cycamore/pull/472
=> Added missing toolkit Position

.gitignore, CMakeLists.txt, src/CMakeLists.txt, src/cyclus.h, src/discovery.cc, src/dynamic_module.cc, src/env.cc.in, src/platform.h.in, src/prog_solver.h, src/prog_translator.h, src/sim_init.cc, src/solver_factory.h, src/toolkit/CMakeLists.txt, src/unix_helper_functions.h, src/version.cc.in, src/windows_helper_functions.h, tests/CMakeLists.txt, tests/agent_tests/agent_tests.h, tests/agent_tests/facility_tests.h, tests/agent_tests/institution_tests.h, tests/agent_tests/region_tests.h, tests/integ_tests.cc, tests/test_minimal_cycle.py, tests/test_null_sink.py, tests/test_source_to_sink.py, tests/test_trivial_cycle.py, tests/toolkit/CMakeLists.txt, tests/tools.py
This PR turns COIN into an optional, compile-time dependency. In the short term (due to a lack of modern BLAS/LAPACK in conda-forge on Windows), this is necessary to allow Cyclus to build on Windows.  Most of the changes here are pretty minor, ug they are in a lot of places throughout the code base.
CC @FlanFlanagan @bam241
=> Make COIN Optional

agents/CMakeLists.txt, cli/CMakeLists.txt, cmake/UseCyclus.cmake, news/ncrb.rst, tests/CMakeLists.txt
This fixes the build system so that ALL of the sources aren't recompiled into the unit tests. This should speed up clean build times considerably.
CC @FlanFlanagan @cyclus/pushers
=> Link against libraries, don't recompile everything

.gitignore, cyclus/agents.pyx, cyclus/cpp_cyclus.pxd, cyclus/lib.pyx, tests/test_toaster.py, tests/toaster.py
This fixes Python agents to enable standard attribute access, such as prototype and parent.
CC @FlanFlanagan @cyclus/pushers
=> Python Agent Attribute Access

INSTALL.rst
There was a typo in the CMake installation instructions
=> fixed typo

src/datum.cc
`timer.h` is not required to compile and run cyclus_unit_test
=> Remove unused dependency

cli/cycpp.py, cmake/UseCyclus.cmake, src/OsiCbcSolverInterface.cpp, src/query_backend.h
Allows to build a conda recipe for cyclus
Also address deprecation from boost 1.68 also.
change in `src/OsiCbcSolverInterface.cpp` were required to build on `condaforge/linux-anvil-comp7`, I don't know if it will break the linux build... 
the change in `cycpp.py` and in `UseCyclus` should be transparent unless you have a `$CPP` variable setup on your system, if so `cmake` will use this value in place of `cpp` executable...
=> bunch of fixes

DEPENDENCIES.rst, circle.yml, docker/cyclus-deps/Dockerfile, src/query_backend.h, tests/cycpp_tests.py
the `jessie-updates` apt-get depots have been archived... This allows to remove them form the sources.list in the `cyclus-build-dpes` docker container
this fix #1504 (docker container already updated accordingly in dockerHub
=> fix docker build_deps

docker/cyclus-ci/Dockerfile
This should fix the deploy_latest job allowing us to get a `cyclus/cyclus` working docker image, which `cycamore` and `cycmetric` CI relies on.
=> Fix deploy_latest job

news/conda_fix.rst
this add the missing news file for the multiple (2 or 3) PR intended to fix CI and the Conda build
=> News for the conda fix PRs

circle.yml, news/news_trigger.rst
This should disable news check after a merge.
Only PRs should trigger news test
=> news check trigger

circle.yml, docker/cyclus-deps/Dockerfile, news/faster_ci.rst
this should improve CI speed by removing installation of `git` and `openssh` in the docker image
=> Improve the CI speed

news/news_test.sh, news/news_test_fix.rst
The news test was somethings failing because it was checking against the origin remote.
if the origin/master was not up-to-date with upstream/master... but the PRed branch was, then the diff was capturing old news file.
this should ensure we always diff the news file against the correct correct `master` branch
*ci is actually pulling owners PR fork not the cyclus repo.*
=> Fix news check

CMakeLists.txt, agents/CMakeLists.txt, circle.yml, cli/CMakeLists.txt, docker/cyclus-deps/Dockerfile, news/py37_compatibility.rst, setup.py, src/CMakeLists.txt, tests/CMakeLists.txt, tests/test_agents/CMakeLists.txt
This resolve #1528 .
sadly it brings back the `cython > 0.27` issue (segfault) ##1512
Note: CI in its actual state will only test the `python3.6(+cython=0.26)` compatibility....
=> Python 3.7 name conflict fix

news/redeclaration_error.rst, src/hdf5_back.cc.in, src/hdf5_back.h.in
I ran into the following issue when compiling Cyclus with GCC and G++ v10.2.1:
```
/home/maxschalz/NVD/cyclus/src/hdf5_back.cc: In member function ‘void cyclus::Hdf5Back::CreateTable(cyclus::Datum*)’:
/home/maxschalz/NVD/cyclus/src/hdf5_back.cc:7672:14: error: redeclaration of ‘template<class _Tp, class _Alloc> class std::__cxx11::list’
7672 |   using std::list;
|              ^~~~
```
When compiling with clang, I did not encounter this problem but the compilation failed for other reasons, so deleting the declaration in `src/hdf5back.cc.in` solved the issue and allowed me to stick with g++.
=> Fix redeclaration error

DEPENDENCIES.rst, news/update-alternatives-single-python-version.rst
I was running into build errors on a fresh Ubuntu 20.04 VM. The fix, helpfully provided by @bam241, was using `update-alternatives` to point `python` at the right version. `DEPENDENCIES.rst` currently makes it seem like the user only needed to use `update-alternatives` if they had both python 2.7 and python3 (3.5) installed on their machine, this PR adds a few lines noting that it may be necessary even with a single version of python installed.
=> use update-alternatives even with single python version

news/fix-macro-and-other-minor-errors.rst, src/hdf5_back.cc.in, src/pyne.h
for issue #1312 - probably doesn't fix it, but contributes to improvements.
=> Fix minor compiler errors (macro expansion, duplicate `using`)

.github/workflows/build_test.yml, .github/workflows/build_test_publish.yml, .github/workflows/publish_release.yml, CHANGELOG.rst, docker/Dockerfile
This PR separates the Cycles workflows into: 
- One that is run from the upstream repo that pushes new dependency images (and is only triggered on changes to the workflow/Dockerfile)
- One that can be run from contributor's forks that pulls the dependency image from cyclus/cyclus package repository, and builds/tests cyclus with those dependencies
I also added a third workflow that is triggered on a release.  It is mostly copied from the build-test-publish.yml, the main differences are the triggers and the image tag
=> Address Issue #1595

.github/workflows/build_test_publish.yml, CHANGELOG.rst
Only run the publish workflow on PRs that have changes in specific files.
Fixes #1600 
(replaces #1601 with local branch)
=> limit PR conditions for running this workflow

CHANGELOG.rst, docker/Dockerfile
Ensure user-site path is created at right stage.
Fix PYTHONPATH to be not hardcoded
Fixes #1610
=> Fix pythonpath

.github/workflows/build_test.yml, .github/workflows/publish_release.yml, CHANGELOG.rst
Relies on #1605  to be merged first.  The `build_test.yml` needs the dependency images for 20.04 to be published as `latest` before all the workflows will pass
=> Add 20.04 support for PR and Publish workflows

CHANGELOG.rst, src/toolkit/matl_buy_policy.cc, src/toolkit/matl_buy_policy.h, tests/toolkit/matl_buy_policy_tests.cc
Two new buy policy parameters, `active` and `dormant`. Both are integers representing a number of time steps.
- For `active` part of the cycle, buying behavior is unchanged
- For `dormant`, agent will not request any new material from DRE
=> Buy policy can cycle back and forth between actively buying and dormant based on time step

CHANGELOG.rst, README.rst
Installation with Ubuntu 22.04 did not work because some conda packages were not compatible anymore.
Followed instructions on the docker installation, and tested it on a clean Ubuntu 22.04 system.
=> Updated Readme file to work properly with Ubuntu 22.04

.github/workflows/build_test.yml, CHANGELOG.rst, CMakeLists.txt, README.rst, install.py
Adds a build option to enable code coverage and generates coverage reports in the `build_test.yml` workflow.
The workflows will generate html artifacts that can be downloaded and push coverage reports to [Coveralls](https://coveralls.io/github/cyclus/cyclus).  The settings in Coveralls allow us to define failure thresholds for PRs.
Fixes #1591
=> Add Code Coverage using Coveralls

CHANGELOG.rst, docker/Dockerfile
Installs pip in the dependency image to support #1632
=> add pip to the dep list in dockerfile

CHANGELOG.rst, docker/Dockerfile
Some changes in the conda dependency tree have resulted in the `libxmlpp` resolving as version 2.40.x and then having an incompatibility with the newest `glibmm`.  This fixes it in local testing.
=> force libxmlpp 4.0 in conda

CHANGELOG.rst, README.rst
The version listed is the lowest version in the 4 builds we have in CI (apt-20.04)
=> Add Zlib as dependency in README

.github/workflows/build_test.yml, .gitignore, CHANGELOG.rst, cyclus/__init__.py, docker/Dockerfile, src/CMakeLists.txt, src/pyhooks.cc
This prevents segmentation faults described in #1589 and removes the `--ignore test_main.py` flag from the python tests in the Dockerfile.  
There are three cython modules in the cython core code - `pymodule.pyx`, `eventhooks.pyx`, and `pyinfile.pyx`.  There is functionality in `pyhooks.cc` that manages the python module initialization.  When cyclus is called from python, the python interpreter is already initialized so these three modules must be imported explicitly (previously "handled" by `py_import_call_init()` in `cyclus/__init__.py`).  This wasn't working correctly, so the cython modules are not appropriately initialized and this is where the segmentation faults occur.  
The current fix builds these three cython modules as their own shared libraries so that python can import them. …
=> Fix Python segmentation fault behavior

.github/workflows/build_test.yml, .github/workflows/code_coverage.yml, .github/workflows/pr_comment.yml, .github/workflows/publish_latest.yml, CHANGELOG.rst
This fixes the CI permissions problems we're seeing (along with cymetric [#195](https://github.com/cyclus/cymetric/pull/195) and cycamore [#583](https://github.com/cyclus/cycamore/pull/583)).  Sorry that this hasn't gone as smoothly as possible, hopefully this is the last major refactor.
Changes are as follows:
- `build_test.yml` does not push any images to the cyclus GHCR.  Instead it uses a local docker registry on the GitHub runner.  This way we don't experience permissions errors with PRs from forks.  This adds a tiny bit of complexity that I wanted to avoid, but honestly I think the workflow might be more intuitive now than in previous iterations.  I tried implementing this without a local registry service but docker automatically tries to pull metadata so I was seeing lots of …
=> CI Updates

.github/workflows/publish_latest.yml, .github/workflows/publish_release.yml, CHANGELOG.rst
In working on #1671 I discovered that I left the `cache-to` line in the incorrect workflow file.  it should be in `publish_latest.yml` so that the cache is updated on every push to `main`
=> cache-to in correct workflow file

CHANGELOG.rst, cyclus/cpp_cyclus.pxd, cyclus/lib.pyx, src/any.hpp, src/cyc_std.h, src/discovery.cc, src/greedy_solver.cc, src/pyhooks.cc, src/pyhooks.h, src/resource_exchange.h
Summary of the changes:
- `src/any.hpp` I found resolution from [newer boost version](https://www.boost.org/doc/libs/1_84_0/boost/spirit/home/support/detail/hold_any.hpp)
- `src/cyc_std.h std::binary_function` is deprecated.  We can just use `std::function` now - https://stackoverflow.com/questions/33114656/replacement-for-stdbinary-function
- `src/greedy_solver.cc` and `src/resource_exchange.h` - `std::bind1st` is deprecated. We can just use `std::bind` now https://stackoverflow.com/questions/52769059/replacement-for-removed-bind1st-in-c17
- `src/discovery.cc` a couple deprecated methods - I followed the suggestions that the warnings listed
- `src/pyhooks.[cc,h]`, `cyclus/cpp_cyclus.pxd`, `cyclus/lib.pyx` - removed a function from pyhooks that we no longer use (and was bad practice given …
=> Resolve compilation warnings in Cyclus build

CHANGELOG.rst, share/cyclus-flat.rng.in, share/cyclus.rng.in, src/context.cc, src/context.h, src/package.cc, src/package.h, src/xml_file_loader.cc, src/xml_file_loader.h, tests/xml_file_loader_tests.cc, tests/xml_file_loader_tests.h
- creates Package class
- packages can be declared in input file (optional)
Closes #1654, closes #1655 
Part of #1620
=> Package class and declaration of packages in input file

.github/workflows/code_coverage.yml, CHANGELOG.rst
I think this will solve the base branch problem we've see with code coverage and PRs.  It seemed to work on my [fork](https://github.com/bennibbelink/cyclus/pull/16).  For some reason coveralls is referencing an [old build](https://coveralls.io/builds/64235833) on `main` which you can see in the coveralls UI.  Removing the explicit reference in the coveralls GitHub action seems to alleviate this issue
=> Remove compare-ref param

CHANGELOG.rst, src/random_number_generator.h, src/toolkit/matl_buy_policy.h
Added typedefs to the random number generator for ease of use
=> typedef for distributions for easier setup by archetypes

CHANGELOG.rst, cli/cycpp.py, tests/cycpp_test.py, tests/test_bear_deploy.py
There are many instances in `cycpp.py` where a standard string is used instead of a raw string literal leading to incorrect escaping.  This led to a failing test mentioned in #1683.  This PR resolves the regex warnings along with a handful of other pytest warnings.  Pytest should run cleanly now with no warnings.
=> Resolve Pytest warnings

CHANGELOG.rst, cli/post-process-cython.py, share/dbtypes_gen.py
Closes #1695 .
Converts a handful of strings uses by `re` to raw string literals to avoid invalid escape sequences.
=> Resolve more regex invalid escape sequences

CHANGELOG.rst, src/context.cc
Built errors into `GetPackageByName` but forgot to do so for `GetPackageById`. Throws for both `id` < 0 and unable to find matching `id`
Closes #1697
=> throw if invalid package id given

CHANGELOG.rst, src/material.h, src/resource.h, src/toolkit/res_buf.h, tests/toolkit/res_buf_tests.cc, tests/toolkit/res_buf_tests.h
Add a state variable to `ResBuf` to declare it as bulk storage with default `false`.  All items that are `Push`ed are automatically `Absorb`ed into the first item in the `ResBuf`.
Also add `Decay` method that will force every item in a `ResBuf` to decay.
=> Allow ResBuf to be a bulk storage facility by forcing a squash of all incoming resources

.github/workflows/build_test.yml, .github/workflows/pr_comment.yml, CHANGELOG.rst
Closes issue #1707.  Adds a timestamp and commit hash to the PR comment generated on downstream testing
=> Add timestamp/SHA to PR comment

CHANGELOG.rst, src/material.cc, src/material.h, src/package.cc, src/package.h, src/product.cc, src/product.h, src/resource.h
=> Unpackaged as default Package id

CHANGELOG.rst, src/package.cc, src/package.h, src/product.cc, tests/package_tests.cc
Some simple tests for Package - hoping for a positive change to coverage!
=> add tests for Package

CHANGELOG.rst, docker/Dockerfile, docker/Rocky.dockerfile
Closes #1733.  Whenever the dependency list changes the `RUN` step will have to re-run and `apt update` the package indexes.
=> Move apt-update to <pkg_mgr>-deps build stage

CHANGELOG.rst, CONTRIBUTING.rst, INSTALL.rst, README.rst
This PR includes some small documentation fixes such as:
* a note in the `CONTRIBUTING` that tells developers to update the CHANGELOG, addressing what was started in #1561 
* fix the formatting for cross referencing in `INSTALL.rst` hat renders correctly on the website and when viewed on GitHub
* change conda package for dependencies to install only the dependencies for the cyclus package, allowing us to not have to maintain a core package and a dependencies package.
* Change the branch name for guiding new developers in the `README`
=> Small documentation fixes

CHANGELOG.rst, README.rst
Closes #1736.  The current instructions in our README say the quickest way to install cyclus is by installing all conda dependencies then build from source.  This changes those instructions to simply `conda install -y cyclus`.
=> Update README conda installation instructions

CHANGELOG.rst, src/res_tracker.cc, src/toolkit/matl_sell_policy.cc
Closes #1760 
Solves root cause issue of [cycamore#611](https://github.com/cyclus/cycamore/issues/611)
Two changes arose out of #1749
1. When materials were fully packaged, the now-zero-quantity old material was recorded as a new resource in the table, even though it was fully absorbed into the new packaged material. This created unexpected zero quantity lines in the Resources database
2. When materials were effectively not packaged (i.e. unpackaged, or going through packaging with the new packaging type equal to the old type), they were still being "packaged" in the sense that they became new resources, with new resource ids and records in the Resources database. The material sell policy would package all trades, meaning that even when packaging wasn't being used, resources were getting …
=> Prevent extra unecessary records in resources database due to packaging

CHANGELOG.rst, docker/Dockerfile
Closes #1762.
Looks like a forced reinstall of libexpat resolves the issue.  This PR also changes the build to use conda-forge::conda which should be more up to date and uses libmamba as the solver by default (can confirm via `conda info`)
One other change - we were using the compilers intended for CentOS.  Now we reference the generic compilers instead.
=> Use miniforge instead of miniconda

CHANGELOG.rst, docker/Dockerfile
Removes the `build/_deps/` directory from coverage reports.  When CMake fetches the GTest source this is where it is placed.
=> Remove GTest source from code coverage

CHANGELOG.rst, share/cyclus-flat.rng.in, share/cyclus.rng.in, src/context.cc, src/context.h, src/package.cc, src/package.h, src/toolkit/matl_sell_policy.cc, src/toolkit/matl_sell_policy.h, src/xml_file_loader.cc, src/xml_file_loader.h, tests/context_tests.cc, tests/package_tests.cc, tests/toolkit/matl_sell_policy_tests.cc, tests/xml_file_loader_tests.cc
Creates new class, `TransportUnit`. Builds on `Package`s, intended to be used to restrict trading to an integer number of packages to mimic a second layer of containerization, such as a truck that holds fuel assembly packages, or a barge that holds spent fuel casks.
Simpler implementation than packages, because transport units are *not* a fundamental property of materials/products, unlike packages. They will be simply applied at the response to request for bids step in `MatlSellPolicy` to make sure that a packages are being shipped in reasonable quantities. For example, shipping 24 UOC drums together instead of shipping 1 drum at a time.
Closes #1660 
Closes #1661
Closes #1624 
Closes #1625 
Closes #1662
=> Transport units

CHANGELOG.rst, src/package.h, src/resource.h, src/toolkit/matl_sell_policy.cc, tests/resource_tests.cc, tests/toolkit/matl_sell_policy_tests.cc
Adds a warning value (1e5) and a limit value (unsigned int / 10) for re-packaging. Implemented in Material Sell Policy, when calculating how many bids to respond with, and in the repackaging process itself (in Resource). If trying (or in the case of sell pol, intending) to repackage a single resource into more than warn/limit values, raise warning/limit
Closes #1766
=> warning and limit for splitting resources into too many packages

CHANGELOG.rst, src/toolkit/res_buf.h, tests/toolkit/res_buf_tests.cc, tests/toolkit/res_buf_tests.h
Replace the `unpackaged` parameter in ResBuf with `keep_packaging`, switching the default from true to false to keep the logic the same.
This reflects the changes that are being made in Reactor and Sink to keep the packaging by default ([cycamore#618](https://github.com/cyclus/cycamore/pull/618))
=> use keep_packaging in resbuf

CHANGELOG.rst, docker/Dockerfile, src/toolkit/res_map.h
Pin boost for now until #1791 is resolved.
This was more complex than anticipated, but now the shell is modified so that we always execute RUN commands inside of a conda env called `cyclus`.  Was running into issues where the compiler was having trouble finding GLIBCXX and this seemed to resolve the issue.  I tried to make it so that it is initializing the conda environment a more traditional way, instead of just setting our path to /opt/conda/bin:$PATH
=> Pin Boost<1.86.0

CHANGELOG.rst, docker/Dockerfile
In trying to build the api docs for cyclus.github.com I was having to rebuild cyclus and cycamore after installing doxygen.  I think it's easier if we just include it in our published images from the start so that the `cyclusdoc` and `cycamoredoc` make targets exist for when we need them downstream.
=> Add doxygen to dependency list in dockerfile

CHANGELOG.rst, src/package.cc, src/package.h, src/resource.h, src/toolkit/matl_sell_policy.cc, src/trade_executor.h, tests/package_tests.cc, tests/toolkit/matl_sell_policy_tests.cc
Addresses @gonuke's comments on [cycamore#621](https://github.com/cyclus/cycamore/pull/621)
Closes #1785 and is part of process for addressing #1786
=> Packaging updates - failed trades send zero material and more robust GetFillMass 

CHANGELOG.rst, src/material.cc, src/material.h, src/package.cc, src/product.cc, src/product.h, src/res_tracker.cc, src/res_tracker.h, src/resource.h, src/toolkit/matl_buy_policy.cc, src/toolkit/matl_sell_policy.cc
Closes #1794. Closes #1797 
Fixes the broken cycamore python tests
~~Still has the failures on conda 22.04 and 24.04 that I don't understand~~
~~#1790 should be merged first~~ (merged)
=> Recording for 1:1 extracted resources

.github/workflows/code_coverage.yml, CHANGELOG.rst
Github actions reports that the current version of `action/upload-pages-artifact` relies on a version of node.js that is soon to be deprecated.  This should resolve that concern.
Fixes #1801
=> update github action version

.gitignore, CHANGELOG.rst, cyclus/__init__.py, cyclus/cpp_cyclus.pxd, cyclus/lib.pyx, src/CMakeLists.txt, src/eventhooks.pxd, src/eventhooks.pyx, src/pyhooks.cc, src/pyhooks.h, src/pyinfile.pxd, src/pyinfile.pyx, src/pymodule.pxd, src/pymodule.pyx
I stumbled upon [this section ](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#c-api-declarations)of the cython docs (I can't believe I missed it before!!) that discusses how to make cython declarations available to C code.  Since we only access cython methods in PyHooks we can define those methods with the `api` keyword and avoid dealing with the messy multi-phase module initialization (see #1781).  It also does not require that `libcyclus` is linked with our cython modules since "the Python import machinery is used to make the connection dynamically" (if you look at the generated `_api.h` headers it looks like they are doing a lot of the messy Python C-API calls that I was making in #1781, but in a robust/correct way :smile:).
This PR replaces #1781 and …
=> Modify Cython api to use `api` keyword 

CHANGELOG.rst, src/res_tracker.cc
Setting parent1 for the removed resource must come before the original resource is recorded. Otherwise, the original (parent) resource becomes its own child, with a new state id. Then that first child becomes the parent1 for the second child.
Closes #1805
=> ResTracker Extract gave the wrong parent_id to one of the child resources

CHANGELOG.rst, share/cyclus-flat.rng.in, share/cyclus.rng.in, src/package.cc, src/package.h, src/resource.h, src/toolkit/matl_sell_policy.cc, tests/package_tests.cc
Closes #1812. Also closes #1777 
Note that the new strategies do not come with any flexibility. The uniform distribution is created with min of `fill_min` and max of `fill_max`. The (truncated) normal distribution is created with mean in the middle of `fill_min` and `fill_max` and its three standard deviations to the boundaries of `fill_min` and `fill_max`. It may be of interest to someone in the future to add user inputs to change these values, but I don't think that's of critical importance now. Or, maybe it's not important enough to be changed later either! 
Because the distributions are dependent on the package values of `fill_min` and `fill_max`, they do not sample when less than `fill_max` of material is available. Otherwise, we would be sampling from only part of the distribution …
=> Add normal and uniform packaging strategies

CHANGELOG.rst, src/cyclus.h
Partially addresses https://github.com/cyclus/cyclus.github.com/issues/389 in conjunction with https://github.com/cyclus/cycamore/pull/632
=> Add link to fuelcycle.org in doxygen homepage

.github/workflows/macos_build_test.yml, CHANGELOG.rst, docker/Dockerfile
Temporarily pin python until other packages have full support for python3.13 (specifically cython(?), see https://github.com/cyclus/cyclus/issues/1824#issuecomment-2440267587)
=> Pin `python<3.13` in CI

CHANGELOG.rst, src/toolkit/matl_buy_policy.cc, src/toolkit/matl_buy_policy.h, tests/toolkit/matl_buy_policy_tests.cc
Introduce methods that allow us to reset a buy policy in case we want to initialize it with better behavior.
Also allow us to unset a specific commodity.
=> add methods to reset/unset build policy

CHANGELOG.rst, src/toolkit/res_buf.h, tests/material_tests.cc, tests/material_tests.h
The new `Decay()` method added to `ResBuf` had a syntax error for `std::list` but was never exposed because templating meant that it was never compiled.
This fixes the loop over the contents of the buffer and adds a test.  The test was added to `material_tests.cc` because it already had all the infrastructure for testing decay.
Closes #1823 (but not in the way it intended)
=> Fix ResBuf Decay

CHANGELOG.rst, src/sqlite_back.cc, tests/sqlite_back_tests.cc
Closes https://github.com/cyclus/cymetric/issues/205.  
I think there must be some inconsistency with how `libc++` and `libboost` handle default locales.  This PR calls `ss.imbue()` to set the locale according to the user's environment, which seems to solve the segfault describe in https://github.com/cyclus/cymetric/issues/205 (at least when I build and test on my arm Mac machine).  We could hardcode this to the "C" locale if we want to make it more robust.  The instance where I could see issues arising is if a user runs a sim in one environment then reads the SQLite DB in a different environment with a different locale.
=> Set locale before (de)serializing data for SQLite

CHANGELOG.rst, docker/Dockerfile
The latest miniforge release upgrades to mamba v2, which has a slightly different CLI than v1.  Seeing the publish_latest.yml workflow fail after #1837.  This PR updates the Dockerfile to conform to both versions of the mamba CLI.  The biggest discrepancy was the method to initialize the shell (`mamba init bash` vs. `mamba shell init --shell bash`), but since we change the Dockerfile shell to run all commands within `mamba run -n cyclus /bin/bash -c ...` we don't actually have to make any changes to the `.bashrc` within the container.
=> Update mamba management in Dockerfile to reflect new mamba cli

.github/workflows/macos_build_test.yml, CHANGELOG.rst, agents/sink.h, cli/cyclus.cc, cli/cycpp.py, docker/Dockerfile, share/cyclus-flat.rng.in, share/cyclus.rng.in, src/xml_file_loader.cc, src/xml_file_loader.h, src/xml_flat_loader.cc, src/xml_flat_loader.h, tests/agent_tests/agent_tests.cc
Fixes #1598
Create two ways to build a master schema:
1. using the agent specs included in an input file
2. using all the agent specs that are discoverable on a system
Change the CLI to use the second option above instead of just regurgitating the schema template.
This has been broken since #843 (11 years!!)
Prior to this, when requesting the schema, Cyclus would load and write the "template" that included lines like `@Facility_REFS@` that are meant to be replaced by the list of available facilities.
Now, those template codes have been replaced and include the full list of choices of available archetypes of each type.
Also automatically adds variable documentation as RelaxNG annotations for each variable, and added some annotations to the template.
=> Fix ability to generate a master schema

CHANGELOG.rst, src/toolkit/position.cc, src/toolkit/position.cycpp.h, src/toolkit/position.h, tests/toolkit/position_tests.cc
This PR primarily serves to reopen discussion on the "correct" way to do code injection through the .cycpp system, specifically related to the initialization of variables in position. A few minor changes were made to the way @bam241 did things, mostly to bring the code in line with some of the in-person talks @gonuke and I had when talking about cyclus/cycamore#502.
- cyclus/cycamore#502
- #1853 
- #1510 
- Closes #1871   
@bam241 
@gonuke 
I attempted to remove all initialization from the constructor (the `latitude(0.0), longitude(0.0), coordinates(0, 0)` bit), but because of limitations with the `#pragma cyclus var` system, it is impossible to inject something like `double latitude = 0.0` (it throws an error). I was able to remove the `coordinates(0, 0)` bit, and …
=> Position Code Injection Variable Initialization Changes

CHANGELOG.rst, src/context.h
A new variable (`cyclusYear`) was added to the Cyclus context such that one `cyclusYear` is four seconds longer than a Gaussian year. This was done in response to something I flagged in #1804 where the old definition of a `kDefaultTimestepDur` wasn't any multiple of a standard year (365.0 days, 1 sidereal year, 1 sidereal month, 1 gaussian year, etc). `kDefaultTimestepDur` was then redefined as 1/12 `cyclusYear`s.  
- Closes #1804  
None.
The reason I defined the `cyclusYear` as four seconds longer than a Gaussian year was so that it was roundly divisible by 12, since our default tilmestep is a month. The alternative was to make it 8 seconds shorter, which is the behavior you would get if you made 1 `cyclusYear` exactly 1 Gaussian year (since int division truncates …
=> Update Definition of a Year to be Gaussian (+4s)

CHANGELOG.rst, src/toolkit/facility_cost.cycpp.h
This very simple PR does two things:
1. Add a CalcUnitPrice() function to distinguish between a cost and a price for a bid (currently implements "default" behavior of just returning the cost)
2. Changes the bit in CalcUnitCost() where `kDefaultTimestepDur * 12` was used for the length of a year to just use `cyclusYear` now that #1867 has been merged. 
- Closes #1876
- #1867 
- #1870   
None.
I made CalcBidPrice() take the same arguments as CalcBidCost() because it seemed like the easiest thing to do. If anyone can think of a better way to do this let me know and I'm happy to change that.
The code was built locally on my machine. No tests have been added.
Reviewers, please refer to the Cyclus [Guide for Reviewers](https://fuelcycle.org/kernel/pr_review.html).
=> Calculate Unit Price

CHANGELOG.rst, src/economic_entity.h, src/toolkit/facility_cost.cycpp.h
After our conversation today, @gonuke and I decided that (one of) the reason(s) that cyclus/cycamore#656 was failing tests was because of a misimplementation of the `CalculateBidPrice()` function in `facility_cost.cycpp.h`, and that what we really wanted was to give it the UnitCost directly so that the default behavior of that function would interact correctly with the expected default behavior of the DRE in the regression tests. As a result, the `CalculateBidCost()` function was changed to `CalculateUnitCost()` (with appropriate modifications therein) and cyclus/cycamore#656 was modified to reflect this change. Hopefully those will stop failing tests now, but before they do, this PR needs to be merged.
- cyclus/cycamore#656
- Closes #1888 
@gonuke 
Changed the …
=> Change Facility_Cost `CalculateBidPrice()` function to `CalculateUnitPrice()`

CHANGELOG.rst, docker/Dockerfile
Changes the conda section of the Dockerfile to grab `boost` and `boost-cpp` instead of `libboost-devel`, which changed recently and was causing issues with the CI testing.
- Closes #1901 
- Closes #1902 
- Closes #1904 
ChatGPT (helped parse error messages)
Not TOTALLY sure about the root cause, but it does seem like libboost-devel was updated around the time this error started popping up, and the errors were pretty consistently saying boost was the problem, so I went in and changed the way we install boost in conda and it seems like it worked.
Made a Test PR to see if this change to the Dockerfile would pass the tests and it did. I cannot get these to compile and run locally, but I can't get ANY of the Dockerfiles to do that, so I'm not certain what I'm doing …
=> Fix Conda CI

CHANGELOG.rst, src/toolkit/facility_cost.cycpp.h, src/toolkit/institution_cost.cycpp.h
The equations added in CalculateUnitCost() require some complete documentation, ideally in the code, that describes the assumptions and derivations used to arrive at the final annualized costs. This PR adds that documentation.
- Closes #1890  
Tried to keep the documentation in the form of a Doxygen comment, and also match the [LaTeX document](https://www.overleaf.com/project/6880ee132697998dfdcbdbf8) as best as possible. Not sure that link will work for anyone who isn't @gonuke but I doubt many people besides him will need to look at it.
Built and tested Cyclus on my local machine. Because the only change here is a comment, I did not do a clean build (it takes a really long time).
Reviewers, please refer to the Cyclus [Guide for …
=> Document Financial Equations in `facility_cost.cycpp.h`

CHANGELOG.rst, src/exchange_manager.h, src/trade_executor.h, tests/trade_executor_tests.cc
While playing with something else, I noticed that when I was adjusting the preference of trades the `RecordTrades()` function, which writes to the Transactions table in the database wasn't reflecting the adjusted cost, but was instead simply recording the original bid cost *before* the adjustment. I am not certain that we will necessarily want to represent this cost as "real", but it would be nice to be able to have access to it. For now, I had Cursor go in and give that function access to the exchange context of the DRE so it can see the adjusted cost, and changed "RecordTrades" to record this cost (if it was adjusted, and otherwise just the normal cost). I looked at what it did, and it more or less made sense and didn't seem too wild, so I figured I'd make a PR since this is a pretty …
=> Allow Cyclus to Record the Adjusted Preference/Cost of Trades
