src/hdf5_back.cc
src/hdf5_back.h
src/query_backend.h
src/sqlite_back.cc
src/sqlite_back.h
tests/hdf5_back_tests.cc
tests/sqlite_back_tests.cc

Yet another QueryableBackend API improvement for querying what tables actually exist. Depends on #1062.

Query existing Tables 

---

cli/cycpp.py
src/hdf5_back.cc
src/hdf5_back.h
src/query_backend.h
tests/cycpp_tests.py
tests/hdf5_back_tests.cc

added pair<int, string> for starters

---

cli/cycpp.py
tests/cycpp_tests.py

This PR fixes significant issues with the default value handling in cycpp.  This was discovered by trying to install bright-lite with the develop version of cyclus. Perhaps @FlanFlanagan would like to take a look.

Much Improved Default Values

---

src/hdf5_back.cc

Minor implementation fix that enables reading in variable-length data in outside of a simulation context.  This is ridiculously urgent. Since it affects @opotowsky, she should probably review, though given the urgency any one is welcome to do the honors. Thanks.

hotfix for reading in variable-length data

---

src/cyclus.h
src/toolkit/timeseries.cc
src/toolkit/timeseries.h
tests/toolkit/timeseries_tests.cc

This implements a time series convention helpers.

TimeSeries

---

src/_pyne_decay.cc
src/_pyne_decay.h
src/pyne.cc
src/pyne.h

Should fix or help fix the nightlies.

re-amalgamates pyne

---

src/agent.h
src/institution.cc

Also - smarter decom handling in inst class - now supports non-facility subclass children.

Agent::lifetime_ now protected to support deploy inst lifetime setting.

---

install.py

Useful for passing definitions directly down to CMake. Taken from pyne.

added -D to install.py

---

src/query_backend.h

should be a simple one. @opotowsky wana take a crack? (or anyone else!)

better error message for row overflow

---

.travis-install.sh
.travis.yml
CMakeLists.txt
cmake/FindHDF5.cmake

Reopening PR that had failed.  Hopefully this will just work.

Revert "Revert "Travis merge""

---

cli/cycpp.py
tests/cycpp_tests.py

...so filters can tweak behavior depending on mode. Snapshoting now omits return statement if operating in impl mode.

Store mode (def, decl, impl) on codegenfilter 

---

README.rst

I feel that while the threat of flogging is funny, it's not totally appropriate and gives the wrong impression of what is actually a very kind, welcoming, culturally sensitive cyclus community.
Again, sorry. I know you're trying to get a release out. I was just too swamped earlier to get around to looking over these main documentation issues. take it or leave it.

just for general community flavor, slight change to readme

---

cli/cycpp.py
tests/cycpp_tests.py

This should be helpful to @FlanFlanagan.

Canonizes and dumps alias, always.

---

src/toolkit/matl_buy_policy.cc
src/toolkit/matl_buy_policy.h

expand on Set API in material buy policy with defaults

---

src/toolkit/matl_buy_policy.cc
src/toolkit/matl_buy_policy.h
src/toolkit/matl_sell_policy.cc
src/toolkit/matl_sell_policy.h
tests/toolkit/matl_buy_policy_tests.cc
tests/toolkit/matl_sell_policy_tests.cc

hotfix for policies using resource buffers

make policies use resbufs

---

agents/sink.cc
agents/source.cc
src/timer.cc
src/toolkit/matl_buy_policy.cc
src/toolkit/matl_sell_policy.cc

more consistent/better logging levels

---

src/toolkit/symbolic_function_factories.h

Better documentation for function factories.

update docs for linear/exp functions

---

install.py

add config-only option

---

agents/prey.h
cli/cycpp.py
src/prettyprint.hpp

With all these recursive containers and various bugs flying around, this is a nice diagnostic tool.

adding prettyprint

---

agents/k_facility.h
agents/predator.h
agents/prey.h
agents/sink.h
agents/source.h

Added uilabels to pragma variables, reordered variables to be logical in Cycic, and wrapped some lines.

added uilabels and reordered for Cycic

---

src/pyne.cc
src/pyne.h

update amalgamated pyne to pyne/pyne:0cbc4a3

---

src/hdf5_back.h
src/query_backend.h
src/rec_backend.h
src/sqlite_back.h
tests/recorder_tests.cc

@rwcarlsen and/or @hodger please take a look at this.

close refactor

---

src/mock_sim.cc

so the context has the correct sim_info struct for agents to query.

fix mocksim to initialize timer via context InitSim

---

CMakeLists.txt
cmake/UseCyclus.cmake

fail fast on more cmake EXECUTE_PROCESS calls

---

src/query_backend.h
src/sqlite_back.cc
tests/sqlite_back_tests.cc

This datatype is needed for some of my mbmore archetypes

Map string map string int

---

share/CMakeLists.txt

Show download progress to prevent CI timeout

---

install.py

Relatively minor change so that the input files are exactly the same.

Ensure that cyclus and cycamore install.py files are the same

---

src/CMakeLists.txt
src/hdf5_back.cc.in
src/hdf5_back_gen.py

Also fixed generated code indentation.
This addresses #1287.

Build will fail on HDF5_back_gen failure

---

src/request.h
src/request_portfolio.h
tests/request_portfolio_tests.cc
tests/request_tests.cc

Added cost function pointer to request.

---

src/material.cc
src/pyne.cc
src/pyne.h

pyne update

---

AUTHORS.rst

Adding @mbmcgarry and myself as author

New author in the list

---

INSTALL.rst

reverting some change: changing  CMake link into `CMake`

link to box for CMake

---

AUTHORS.rst
CONTRIBUTING.rst
DEPENDENCIES.rst
INSTALL.rst
LICENSE.rst
README.rst

Pphw dox review

---

CONTRIBUTING.rst
DEPENDENCIES.rst
INSTALL.rst
README.rst

update the Ubuntu/MacOSX version on which test have been performed.

V1.4.0 release

---

INSTALL.rst
README.rst

This should be coordinated with a similar PR in the website docs

Pphw dox rev2

---

DEPENDENCIES.rst

Small formatting changes to fix RST errors when building into website

Fix rst err

---

DEPENDENCIES.rst
circle.yml

remove ubuntu 14.04 mention in documentation

---

release/smbchk.py

string stream were lost somewhere...

add stringstream to symbol repl

---

INSTALL.rst
README.rst

update documentation for PYTHONPATH on macos

PYTHONPATH update for macOS

---

circle.yml
cli/cyclus.cc
src/eventhooks.pxd
src/eventhooks.pyx
src/mock_sim.cc
src/pyhooks.h
tests/full_sim_tests.cc
tests/integ_tests.cc
tests/material_tests.cc
tests/material_tests.h
tests/sim_init_tests.cc
tests/test_include_recipe.py
tests/test_inventories.py
tests/test_lotka_volterra.py
tests/test_minimal_cycle.py
tests/test_null_sink.py
tests/test_source_to_sink.py
tests/test_trivial_cycle.py
tests/timer_tests.cc
tests/tools.py

This may address #1372 @mbmcgarry @Baaaaam

startup python in mocksim

---

docker/cyclus-deps/Dockerfile

Needed to avoid deprecation issues.

Updated cython to most recent version

---

cyclus/agents.pyx
cyclus/cpp_cyclus.pxd
cyclus/gentypesystem.py
cyclus/lib.pyx

Some minor bits I missed before. @FlanFlanagan @bam241 @hodger

More Python Wrapping.

---

cyclus/cpp_cyclus.pxd
cyclus/lib.pxd
cyclus/lib.pyx
src/hdf5_back.cc.in
src/hdf5_back.h.in
src/query_backend.h
src/sqlite_back.cc
src/sqlite_back.h
tests/test_cycluslib.py

@scopatz 
Ability to retrieve information regarding shape, column names, etc.

Added Schema + tests to QueryableBackend

---

agents/sink.h
agents/source.h
circle.yml
cli/cycpp.py
docker/cyclus-ci/Dockerfile
tests/test_abi.py

Needed for progress on cycamore

allow in/out recipes

---

cyclus/lib.pyx

Parameters typo

---

tests/toolkit/timeseries_tests.cc

This should fix #1382.  CC @orpheus92 @FlanFlanagan @bam241

Timeseries test fix

---

src/CMakeLists.txt

This should address #1389, temporarily.

Transmutagen working fix to compile with clang

---

CMakeLists.txt
cmake/FindPandas.cmake

Check for pandas if cython is found

---

cli/cyclus.cc
cyclus/cpp_cyclus.pxd
cyclus/lib.pyx
cyclus/main.py
cyclus/simstate.py
src/xml_file_loader.cc
src/xml_file_loader.h
src/xml_flat_loader.h
tests/xml_file_loader_tests.cc

Allows a user to print out the master scheme for a simulation. Terminates the cyclus run after the schema is printed.

first cut at rng print

---

cyclus/simstate.py

minor bug fix @FlanFlanagan @bam241 @orpheus92

ns -> self

---

INSTALL.rst

This is related to #1408.
If this is unnecessary or out of place, please let me know.

Added instructions when installing Cyclus with conda libraries

---

circle.yml

**docker 17.06.1-ce (2017-08-15) changelog**: 
...
[Remove deprecated --email flag from docker login #docker/cli/143](https://docs.docker.com/release-notes/docker-ce/#17060-ce-2017-06-28)
...
@scopatz there is the fix.

remove -e flag in docker login

---

CONTRIBUTING.rst
circle.yml

Some transitions needed for migrating from develop to master. CC @bam241

Develop to master

---

cyclus/cpp_cyclus.pxd
cyclus/gentypesystem.py
cyclus/lib.pyx
src/pyhooks.cc
src/pyhooks.h
src/pymodule.pxd
src/pymodule.pyx
src/toolkit/timeseries.cc
src/toolkit/timeseries.h
tests/dummy_power_recorder.py

This allows the new time series recorder system to take more  than just the cyclus timeseriestypes.

Boost variant

---

cyclus/lib.pyx

fixes an issue with the string timeseries recorders

prevents expected bytes got string error

---

news/PR1453.rst
src/toolkit/position.cc
src/toolkit/position.h
tests/toolkit/position_tests.cc

Fixes #1452 .
The PR now adds a THROW_Value statement that checks whether the longitude and latitude are within acceptable range. 
Tests to confirm these exceptions were also added in the test file.

Input validation for Position toolkit

---

cyclus/agents.pyx
news/nonecap.rst

fix for none values inventory capacities

---

cyclus/gentypesystem.py
news/segfault.rst
share/dbtypes_gen.py
src/hdf5_back_gen.py
src/query_backend.h

CC @FlanFlanagan @bam241 @gonuke

Segfaulting Fix for some high-numbered dbtyes in Python

---

cyclus/cpp_cyclus.pxd
cyclus/lib.pxd
cyclus/lib.pyx
news/pypos.rst
tests/test_cycluslib.py

This adds Python bindings for the new position class. CC @FlanFlanagan @katyhuff @gyutaepark @gwenchee @jbae11

Python Position Binding 

---

cyclus/gentypesystem.py
news/pop.rst

CC @FlanFlanagan Should fix #1465

resource buffer popping fix

---

README.rst
news/readme_update_news.rst

Based off of our findings from Issue #1524, this is an update to the README reflecting the current state of the dependencies.

Update to README with new installation instructions

---

README.rst
news/house_cleaning.rst

Just remove the mention to the different `develop` branches, as we don't use it anymore....

House cleaning

---

news/timeserie_unit.rst
src/timer.cc
src/toolkit/timeseries.cc
src/toolkit/timeseries.h

This adds:
- optional unit when recording Timeserie
- add unit when recording inventory (using the unit embedded in Materials)

Add units 

---

.gitignore
news/new_data_url.rst
share/CMakeLists.txt

updates cyclus_nuc_data.h5 URL after dory retirement...

Updating cyclus_nuc_data.h5 URL

---

.github/workflows/build_test.yml
CHANGELOG.rst

Pull cyclus image from cyclus ghcr

---

CHANGELOG.rst
share/cyclus-flat.rng.in
share/cyclus.rng.in
tests/input/custom_seed.xml
tests/integ_tests.cc

 Add seed and stride to R NG schema

---

CHANGELOG.rst
src/context.cc
src/context.h
src/material.cc
src/material.h
src/package.cc
src/package.h
src/product.cc
src/product.h
src/resource.h

Package ID for resources (materials/products)

---

CHANGELOG.rst
src/material.cc
src/package.cc
src/package.h
src/product.h
src/toolkit/res_buf.h
src/toolkit/res_manip.cc
src/toolkit/res_manip.h
src/xml_file_loader.cc

- First pass at packaging interface with resource buffer
Closes #1657 and closes #1658
Linked to #1620

Packaging with Resource Buffer Pop and Push

---

CHANGELOG.rst
src/context.cc
src/sim_init.cc
src/sim_init.h

Closes #1783. Oops I repeated the same mistake in #1750 as I did in #1749 (not putting packaging in SimInit), which I fix here.

transportunits in siminit

---

CHANGELOG.rst
cmake/UseCython.cmake
cyclus/CMakeLists.txt
src/CMakeLists.txt
src/context.h
src/infile_tree.cc
src/package.cc
src/prog_translator.cc
src/toolkit/building_manager.cc
src/toolkit/matl_sell_policy.cc
tests/CMakeLists.txt
tests/prog_translator_tests.cc

Closes #1808 and #1742, along with cleaning up some other compiler warnings.

Resolve various compiler warnings

---

CHANGELOG.rst
src/random_number_generator.h
tests/toolkit/matl_buy_policy_tests.cc

Adds binomial, negative binomial, poisson, and exponential distributions.
Adds test for negative binomial in the buy policy because I'm going to implement that into cycamore:Storage as a way to model disruptions

More random distributions

---

CHANGELOG.rst
share/cyclus-flat.rng.in
share/cyclus.rng.in
src/xml_file_loader.cc

Remove deprecated `exclusive_orders_only` from schema

---

CHANGELOG.rst
src/random_number_generator.h
tests/toolkit/matl_buy_policy_tests.cc

This adds a new random distribution that samples between two options with a single probability.

Add binary distributions for doubles and integers

---

CHANGELOG.rst
tests/agent_tests/facility_tests.cc
tests/agent_tests/institution_tests.cc

Add GTEST macro to institution tests

---

CHANGELOG.rst
cli/cyclus.cc
share/cyclus-flat.rng.in
share/cyclus.rng.in

Closes #1847
Also takes the opportunity to group the command-line options into logical groupings for easier user parsing/searching

Adds a new command-line option to generate a new file w/ up-to-date grammar
